### ISSUE TITLE
Undefined procedure: andarfrente/2

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#25]
Tentei rodar o agente (ramo develop) e deu esse erro.

Fui tentar ajudar no bug sobre cair nos buracos, mas nem andou, quem dirá cair.

**Comment by aronsales** [comment]
Professor, esse erro em especifico foi dado porque o ''andarfrente" estava em comentário, porém eu venho com um problema o qual aparece 
"External function run_agent([no,no,no,no,no], No Action) failed miserably!"
Mesmo com a ação sendo bem explicita, no caso ''goforward", fiz inúmeros testes no meu feature  com a função em si e nada,penso que pode ser algum erro relacionado com as funções abaixo, estou certo ?

**Comment by aronsales** [comment]
O máximo que eu consegui foi que a função execute uma ação, mas somente uma, por isso penso que o erro pode ser externo á funçao.

**Comment by drbeco** [comment]
**No Action** !

Ué, o predicado `run_agent(Percepcao, Acao)` recebe uma `Percepcao` e deve calcular e retornar uma `Acao`.

Olhe bem a linha 64!

**Comment by aronsales** [comment]
Tava trabalhando com (P,A), mas não tinha atualizado o develop com o meu feature, subi agora pro git, se o senhor poder dar uma olhada, eu seria muito grato

**Comment by aronsales** [comment]
A funçao "andar" só com o goforward funciona, porem quando ela deveria iniciar no ([no,yes,no,no,no], turnright) ela aparece este erro 
External function run_agent([no,yes,no,no,no], No Action) failed miserably!

**Comment by drbeco** [comment]
Ok, se vc entendeu, pode fechar o bug #27 .

**Comment by drbeco** [comment]
Um trace com o erro que você está comentando:

```
   Call: (10) wumpus3:display_world ? skip
-----------------------------------------
|         |     P   |         |     P G |
-----------------------------------------
|         |         | W       |         |
-----------------------------------------
|         |     P   |         |         |
-----------------------------------------
|         |   A     |         |         |
-----------------------------------------
wumpus_health(alive)
agent_location(2,1)
agent_orientation(0)
agent_health(alive)
agent_arrows(1)
agent_gold(0)
   Exit: (10) wumpus3:display_world ? creep
   Call: (10) _G2114 is 1+1 ? creep
   Exit: (10) 2 is 1+1 ? creep
   Call: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
   Call: (11) wumpus3:agent_health(dead) ? creep
   Fail: (11) wumpus3:agent_health(dead) ? creep
   Redo: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
   Call: (11) wumpus3:agent_in_cave(no) ? creep
   Fail: (11) wumpus3:agent_in_cave(no) ? creep
   Redo: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
   Call: (11) wumpus3:max_agent_actions(_G2114) ? creep
   Exit: (11) wumpus3:max_agent_actions(64) ? creep
   Call: (11) 2>64 ? creep
   Fail: (11) 2>64 ? creep
   Redo: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
   Call: (11) run_agent([no, yes, no, no, no], _G2115) ? creep
   Call: (12) write('Percebi: ') ? creep
Percebi: 
   Exit: (12) write('Percebi: ') ? creep
   Call: (12) writeln([no, yes, no, no, no]) ? creep
[no,yes,no,no,no]
   Exit: (12) writeln([no, yes, no, no, no]) ? creep
   Call: (12) casas_seguras(_G2114) ? creep
   Exit: (12) casas_seguras([2, 1]) ? creep
   Call: (12) write('Casas Seguras :') ? creep
Casas Seguras :
   Exit: (12) write('Casas Seguras :') ? creep
   Call: (12) writeln([2, 1]) ? creep
[2,1]
   Exit: (12) writeln([2, 1]) ? creep
   Call: (12) casas_perigosas(_G2120) ? creep
   Exit: (12) casas_perigosas([]) ? creep
   Call: (12) write('Casas Perigosas: ') ? creep
Casas Perigosas: 
   Exit: (12) write('Casas Perigosas: ') ? creep
   Call: (12) writeln([]) ? creep
[]
   Exit: (12) writeln([]) ? creep
   Call: (12) casas_visitadas(_G2120) ? creep
   Exit: (12) casas_visitadas([]) ? creep
   Call: (12) write('Casas Visitadas :') ? creep
Casas Visitadas :
   Exit: (12) write('Casas Visitadas :') ? creep
   Call: (12) writeln([]) ? creep
[]
   Exit: (12) writeln([]) ? creep
   Call: (12) casa_segura([no, yes, no, no, no]) ? creep
   Fail: (12) casa_segura([no, yes, no, no, no]) ? creep
   Fail: (11) run_agent([no, yes, no, no, no], _G2115) ? creep
   Redo: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
^  Call: (11) format([69, 120, 116, 101, 114, 110, 97, 108|...], [[no, yes, no, no, no]]) ? creep
External function run_agent([no,yes,no,no,no], No Action) failed miserably!
^  Exit: (11) format([69, 120, 116, 101, 114, 110, 97, 108|...], [[no, yes, no, no, no]]) ? creep
   Call: (11) fail ? creep
   Fail: (11) fail ? creep
   Fail: (10) wumpus3:run_agent_trial(2, [no, yes, no, no, no]) ? creep
   Fail: (9) wumpus3:run_agent_trial(1, [no, no, no, no, no]) ? creep
   Fail: (8) wumpus3:run_agent_trials(1, 1, _G394) ? creep
   Fail: (7) wumpus3:evaluate_agent(1, _G393) ? creep
   Fail: (6) wumpus3:start ? creep
false.
```

Veja que ele falha em `Call: (12) casa_segura([no, yes, no, no, no])`

Ok?
