### ISSUE TITLE
Atualizando listas (Seguras/Visitadas)

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#28]
Ao ativar um `trace` no PROLOG, recebi este retorno das funções chamadas:

```
   Call: (10) run_agent([no, no, no, no, no], _G1687) ? creep
   Call: (11) write('Percebi: ') ? creep
Percebi: 
   Exit: (11) write('Percebi: ') ? creep
   Call: (11) writeln([no, no, no, no, no]) ? creep
[no,no,no,no,no]
   Exit: (11) writeln([no, no, no, no, no]) ? creep
   Call: (11) casas_seguras(_G1686) ? creep
   Exit: (11) casas_seguras([]) ? creep
   Call: (11) write('Casas Seguras :') ? creep
Casas Seguras :
   Exit: (11) write('Casas Seguras :') ? creep
   Call: (11) writeln([]) ? creep
[]
   Exit: (11) writeln([]) ? creep
   Call: (11) casas_perigosas(_G1686) ? creep
   Exit: (11) casas_perigosas([]) ? creep
   Call: (11) write('Casas Perigosas: ') ? creep
Casas Perigosas: 
   Exit: (11) write('Casas Perigosas: ') ? creep
   Call: (11) writeln([]) ? creep
[]
   Exit: (11) writeln([]) ? creep
   Call: (11) casas_visitadas(_G1686) ? creep
   Exit: (11) casas_visitadas([]) ? creep
   Call: (11) write('Casas Visitadas :') ? creep
Casas Visitadas :
   Exit: (11) write('Casas Visitadas :') ? creep
   Call: (11) writeln([]) ? creep
[]
   Exit: (11) writeln([]) ? creep
   Call: (11) casa_segura([no, no, no, no, no]) ? creep
   Call: (12) casas_seguras(_G1686) ? creep
   Exit: (12) casas_seguras([]) ? creep
   Call: (12) posicao(_G1686, _G1687) ? creep
   Exit: (12) posicao(1, 1) ? creep
   Call: (12) orientacao(0) ? creep
   Exit: (12) orientacao(0) ? creep
   Call: (12) _G1689 is 1+1 ? creep
   Exit: (12) 2 is 1+1 ? creep
   Call: (12) 1<4 ? creep
   Exit: (12) 1<4 ? creep
^  Call: (12) not(member([2, 1], [])) ? creep
^  Exit: (12) not(user:member([2, 1], [])) ? creep
   Call: (12) lists:append([], [[2, 1]], _G1712) ? creep
   Exit: (12) lists:append([], [[2, 1]], [[2, 1]]) ? creep
^  Call: (12) retractall(casas_seguras(_G1703)) ? creep
^  Exit: (12) retractall(casas_seguras(_G1703)) ? creep
^  Call: (12) assert(casas_seguras([[2, 1]])) ? creep
^  Exit: (12) assert(casas_seguras([[2, 1]])) ? creep
   Exit: (11) casa_segura([no, no, no, no, no]) ? creep
   Call: (11) andarfrente([no, no, no, no, no], _G1715) ? creep
   Exit: (11) andarfrente([no, no, no, no, no], goforward) ? creep
   Exit: (10) run_agent([no, no, no, no, no], _G1715) ? creep
```

Repare que ao final o predicado `casas_seguras([[2,1]])` tem apenas a casa `[2,1]`. Não está faltando a casa `[1,1]`? E o mesmo vale para `casas_visitadas` que tem apenas a lista vazia, mas ao entrar o agente já automaticamente visita a casa `[1,1]`, não é?
